# permissions for end users to edit ats.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: at-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: go-operator
    app.kubernetes.io/part-of: go-operator
    app.kubernetes.io/managed-by: kustomize
  name: at-editor-role
rules:
- apiGroups:
  - cnat.programming-kubernetes.info
  resources:
  - ats
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cnat.programming-kubernetes.info
  resources:
  - ats/status
  verbs:
  - get
